// ===== DATA =====
// فقط IDs بدون عناوين — تُجلب تلقائياً من YouTube oEmbed
const DATA_RAW = {
  "مشاري العفاسي": [
    { id: "JFJDsmO1Yjk&list", category: "مشاري العفاسي" },
    { id: "Zrovi_d3WQQ&list", category: "مشاري العفاسي" },
    { id: "pyj9FW9fQ7Y&list", category: "مشاري العفاسي" },
    { id: "YVZhSvxbZrc&list", category: "مشاري العفاسي" },
    { id: "3KsdiYsKSQA&list", category: "مشاري العفاسي" },
    { id: "3Uw2RbUfwsM&list", category: "مشاري العفاسي" },
    { id: "tqE_AmepCT4&list", category: "مشاري العفاسي" },
    { id: "OEaTS_Q_28Y&list", category: "مشاري العفاسي" },
    { id: "iPl_NVXvznU&list", category: "مشاري العفاسي" },
    { id: "ToF0gpJFn5o&list", category: "مشاري العفاسي" },
    { id: "AFckiMfJtic&list", category: "مشاري العفاسي" },
    { id: "wPyk7C5wMa8&list", category: "مشاري العفاسي" },
    { id: "v84GDcDUUvY&list", category: "مشاري العفاسي" },
    { id: "IILNhV0y4sA&list", category: "مشاري العفاسي" },
    { id: "SK8fYriIrTw&list", category: "مشاري العفاسي" },
    { id: "Ev5oQyqFT9c&list", category: "مشاري العفاسي" },
    { id: "Pb62zKNo7Hc&list", category: "مشاري العفاسي" },
    { id: "ArM9kZXM-eI&list", category: "مشاري العفاسي" },
    { id: "TOv2VbsHtYQ&list", category: "مشاري العفاسي" },
    { id: "IlC8SnzCbAA&list", category: "مشاري العفاسي" },
    { id: "jN7wuZTlvug&list", category: "مشاري العفاسي" },
    { id: "4aFSwBRGWe8&list", category: "مشاري العفاسي" },
    { id: "_NCG7ZYHdmE&list", category: "مشاري العفاسي" },
    { id: "L_uxwDeLFqw&list", category: "مشاري العفاسي" },
    { id: "GFyoyMD_l3w&list", category: "مشاري العفاسي" },
    { id: "juSYtdn2fX8&list", category: "مشاري العفاسي" },
    { id: "k_d2hkSNT3g&list", category: "مشاري العفاسي" },
    { id: "30CVCRXAsXs&list", category: "مشاري العفاسي" },
    { id: "eiqGUmNJF7M&list", category: "مشاري العفاسي" },
    { id: "krrPH43k3Ys&list", category: "مشاري العفاسي" },
    { id: "dEJbV_ru7S4&list", category: "مشاري العفاسي" },
    { id: "320gzbsmF-g&list", category: "مشاري العفاسي" },
    { id: "pBqYlZ1e-JM&list", category: "مشاري العفاسي" },
    { id: "167pU1gkQ-s&list", category: "مشاري العفاسي" },
    { id: "GefpTcWvpdQ&list", category: "مشاري العفاسي" },
    { id: "iuW_LFaNIjU&list", category: "مشاري العفاسي" },
    { id: "DI2_KF6QUy4&list", category: "مشاري العفاسي" },
    { id: "9gpk_eurUag&list", category: "مشاري العفاسي" },
    { id: "NxYCrFTN45M&list", category: "مشاري العفاسي" },
    { id: "AUFxDPi4TUE&list", category: "مشاري العفاسي" },
    { id: "6NV8ly32ueg&list", category: "مشاري العفاسي" },
    { id: "vuyHEQKg3bg&list", category: "مشاري العفاسي" },
    { id: "eUatnrlS3iU&list", category: "مشاري العفاسي" },
    { id: "V57HAqzwbbY&list", category: "مشاري العفاسي" },
    { id: "ByMYO_p1VLw&list", category: "مشاري العفاسي" },
    { id: "4lvjTYz36MY&list", category: "مشاري العفاسي" },
    { id: "PW-q-fqyCCw&list", category: "مشاري العفاسي" },
    { id: "VewPMR0G1dI&list", category: "مشاري العفاسي" },
    { id: "M9wYQNCcm80&list", category: "مشاري العفاسي" },
    { id: "a1U-k4T3H_U&list", category: "مشاري العفاسي" },
    { id: "MCmq9x1iprw&list", category: "مشاري العفاسي" },
    { id: "FNs3UTXARJE&list", category: "مشاري العفاسي" },
    { id: "a1QfuQpx90U&list", category: "مشاري العفاسي" },
    { id: "HPbI2ZaxMTc&list", category: "مشاري العفاسي" },
    { id: "GWGWwnFjTnk&list", category: "مشاري العفاسي" },
    { id: "Uohs4WQP2ik&list", category: "مشاري العفاسي" },
    { id: "L0xfItStMnk&list", category: "مشاري العفاسي" },
    { id: "bLvfF161Hiw&list", category: "مشاري العفاسي" },
    { id: "wJuLEQVM1cc&list", category: "مشاري العفاسي" },
    { id: "u_6NfVYxk6I&list", category: "مشاري العفاسي" },
    { id: "2ZKX0E6KdhQ&list", category: "مشاري العفاسي" },
    { id: "B65aKC8PHos&list", category: "مشاري العفاسي" },
    { id: "dG-mGcjK3Xc&list", category: "مشاري العفاسي" },
    { id: "HKLNBF8ooQg&list", category: "مشاري العفاسي" },
    { id: "HdGWKfJKRKs&list", category: "مشاري العفاسي" },
    { id: "qh1dIfnMyRA&list", category: "مشاري العفاسي" },
    { id: "3kiZv_CXoc4&list", category: "مشاري العفاسي" },
    { id: "4rYSnPsuP4s&list", category: "مشاري العفاسي" },
    { id: "1KpPfYFd2zE&list", category: "مشاري العفاسي" },
    { id: "LIcUWTA_b7U&list", category: "مشاري العفاسي" },
    { id: "yuRShVQKwU4&list", category: "مشاري العفاسي" },
    { id: "yO6zaniz_2c&list", category: "مشاري العفاسي" },
    { id: "yevEesJf9Qw&list", category: "مشاري العفاسي" },
    { id: "ryiuXQutVLk&list", category: "مشاري العفاسي" },
    { id: "TASASMWBj50&list", category: "مشاري العفاسي" },
    { id: "E0D9pFck21c&list", category: "مشاري العفاسي" },
    { id: "8cUdhjmF1fo&list", category: "مشاري العفاسي" },
    { id: "f7yaXpTYCO4&list", category: "مشاري العفاسي" },
    { id: "BJn1l2P2R4c&list", category: "مشاري العفاسي" },
    { id: "2tzCsVQUHsg&list", category: "مشاري العفاسي" },
    { id: "tKWr_lbZu9g&list", category: "مشاري العفاسي" },
    { id: "Xof4XD3zksQ&list", category: "مشاري العفاسي" },
    { id: "-Bn4y_Y5ISo&list", category: "مشاري العفاسي" },
    { id: "wfy6xVB3QX0&list", category: "مشاري العفاسي" },
    { id: "Tx_jQoBqY-s&list", category: "مشاري العفاسي" },
    { id: "anA3rx_Kk2s&list", category: "مشاري العفاسي" },
    { id: "mrkWan4r2_8&list", category: "مشاري العفاسي" },
    { id: "bhOjdNE-ZcM&list", category: "مشاري العفاسي" },
    { id: "ZwOdb0RapyQ&list", category: "مشاري العفاسي" },
    { id: "WKRVv8IJzLE&list", category: "مشاري العفاسي" },
    { id: "aMP3UjP_HaI&list", category: "مشاري العفاسي" },
    { id: "LfSOBj97_2w&list", category: "مشاري العفاسي" },
    { id: "ZbOTxVIv92U&list", category: "مشاري العفاسي" },
    { id: "exXfG-3ET-Q&list", category: "مشاري العفاسي" },
    { id: "t71nVrwexo0&list", category: "مشاري العفاسي" },
    { id: "lch1NAYfUcg&list", category: "مشاري العفاسي" },
    { id: "XYmqfyH3Ivc&list", category: "مشاري العفاسي" },
    { id: "8n3rPyshkYM&list", category: "مشاري العفاسي" },
    { id: "m7x2PCED88M&list", category: "مشاري العفاسي" },
    { id: "F4EVNadUfWk&list", category: "مشاري العفاسي" },
    { id: "Hdg-nv_kSEo&list", category: "مشاري العفاسي" },
    { id: "_nsNRZxEltk&list", category: "مشاري العفاسي" },
    { id: "86edI1cEwHo&list", category: "مشاري العفاسي" },
    { id: "a5DLKSCOCAA&list", category: "مشاري العفاسي" },
    { id: "8ulaQOsGn8g&list", category: "مشاري العفاسي" },
    { id: "jPIUyywawps&list", category: "مشاري العفاسي" },
    { id: "zRdkRoSl7cQ&list", category: "مشاري العفاسي" },
    { id: "jIWOR-6XJMk&list", category: "مشاري العفاسي" },
    { id: "SQnYg7RskF8&list", category: "مشاري العفاسي" },
    { id: "AzlK9dwyrog&list", category: "مشاري العفاسي" },
    { id: "C3KXRuo1AXY&list", category: "مشاري العفاسي" },
    { id: "23cs89pp2BI&list", category: "مشاري العفاسي" },
    { id: "rcgk7kIGN7M&list", category: "مشاري العفاسي" },
    { id: "9wZ4EXVD1xg&list", category: "مشاري العفاسي" },
  ],
  "عبد الباسط عبد الصمد": [
    { id: "fBfeN64JVHo&list", category: "عبد الباسط عبد الصمد" },
    { id: "whEnOg7SOyE&list", category: "عبد الباسط عبد الصمد" },
    { id: "cOT3b5_7YvY&list", category: "عبد الباسط عبد الصمد" },
    { id: "TULsffVXK-8&list", category: "عبد الباسط عبد الصمد" },
    { id: "KgiBsOZaJPY&list", category: "عبد الباسط عبد الصمد" },
    { id: "LT5otEZVR1I&list", category: "عبد الباسط عبد الصمد" },
    { id: "U1RtBB3yZqU&list", category: "عبد الباسط عبد الصمد" },
    { id: "m8iPDWHKoG0&list", category: "عبد الباسط عبد الصمد" },
    { id: "XD9dZ8bColk&list", category: "عبد الباسط عبد الصمد" },
    { id: "t083JY8M0Mg&list", category: "عبد الباسط عبد الصمد" },
    { id: "uIPfrwgcNkw&list", category: "عبد الباسط عبد الصمد" },
    { id: "aTEBp4ZqstY&list", category: "عبد الباسط عبد الصمد" },
    { id: "LxS43tzPIg8&list", category: "عبد الباسط عبد الصمد" },
    { id: "9pmpg9FEHqE&list", category: "عبد الباسط عبد الصمد" },
    { id: "GdGtS7ldF54&list", category: "عبد الباسط عبد الصمد" },
    { id: "j-_9qm7Or3A&list", category: "عبد الباسط عبد الصمد" },
    { id: "4VEAV3GeO3M&list", category: "عبد الباسط عبد الصمد" },
    { id: "UiudX-zZzaU&list", category: "عبد الباسط عبد الصمد" },
    { id: "jNu3dAoc9hc&list", category: "عبد الباسط عبد الصمد" },
    { id: "R0kRYfS93YM&list", category: "عبد الباسط عبد الصمد" },
    { id: "ugNgosGuKJs&list", category: "عبد الباسط عبد الصمد" },
    { id: "gKidO_idmW0&list", category: "عبد الباسط عبد الصمد" },
    { id: "2yT595PNfxE&list", category: "عبد الباسط عبد الصمد" },
    { id: "nauYXvU7WsQ&list", category: "عبد الباسط عبد الصمد" },
    { id: "I8o8h1KfDmk&list", category: "عبد الباسط عبد الصمد" },
    { id: "wZFCWx4De6w&list", category: "عبد الباسط عبد الصمد" },
    { id: "-Nwi3d-0iZ4&list", category: "عبد الباسط عبد الصمد" },
    { id: "t8ce_Hji_ts&list", category: "عبد الباسط عبد الصمد" },
    { id: "o3VBiMeqE2U&list", category: "عبد الباسط عبد الصمد" },
    { id: "ABeJ5nT-Xqg&list", category: "عبد الباسط عبد الصمد" },
    { id: "UtJ-kAYb0q4&list", category: "عبد الباسط عبد الصمد" },
    { id: "i7Q7M8LLKfM&list", category: "عبد الباسط عبد الصمد" },
    { id: "ZC3byjXLRjc&list", category: "عبد الباسط عبد الصمد" },
    { id: "5Ngpc5YZ2Iw&list", category: "عبد الباسط عبد الصمد" },
    { id: "DetpK1Dh40E&list", category: "عبد الباسط عبد الصمد" },
    { id: "TLw9j-6L9SU&list", category: "عبد الباسط عبد الصمد" },
    { id: "n1VCRvLJTa8&list", category: "عبد الباسط عبد الصمد" },
    { id: "aZB-fsgXcdo&list", category: "عبد الباسط عبد الصمد" },
    { id: "gpkp884vsBI&list", category: "عبد الباسط عبد الصمد" },
    { id: "fgeNvEMNrNY&list", category: "عبد الباسط عبد الصمد" },
    { id: "ZdSy_x7UIcE&list", category: "عبد الباسط عبد الصمد" },
    { id: "VlMWJOGIk2Q&list", category: "عبد الباسط عبد الصمد" },
    { id: "eMAP_W5gXj8&list", category: "عبد الباسط عبد الصمد" },
    { id: "VtL07UJjDcU&list", category: "عبد الباسط عبد الصمد" },
    { id: "AU2SLLyvH9g&list", category: "عبد الباسط عبد الصمد" },
    { id: "5edmWhdynq4&list", category: "عبد الباسط عبد الصمد" },
    { id: "tPKMdjTNQz0&list", category: "عبد الباسط عبد الصمد" },
    { id: "kC4oQ5FBr2E&list", category: "عبد الباسط عبد الصمد" },
    { id: "BfnRAXZ05KM&list", category: "عبد الباسط عبد الصمد" },
    { id: "YiYMoQ3cZgA&list", category: "عبد الباسط عبد الصمد" },
    { id: "BF62wNP-PIA&list", category: "عبد الباسط عبد الصمد" },
    { id: "DQYwNOW8qWc&list", category: "عبد الباسط عبد الصمد" },
    { id: "H98Dx1zI93Y&list", category: "عبد الباسط عبد الصمد" },
    { id: "zZgsRmAO3co&list", category: "عبد الباسط عبد الصمد" },
    { id: "SZyDt8FQt1o&list", category: "عبد الباسط عبد الصمد" },
    { id: "fPcrTOz2YLA&list", category: "عبد الباسط عبد الصمد" },
    { id: "w1pr0UYFcts&list", category: "عبد الباسط عبد الصمد" },
    { id: "ebXcmcEd9uc&list", category: "عبد الباسط عبد الصمد" },
    { id: "9PnH7TF6eEc&list", category: "عبد الباسط عبد الصمد" },
    { id: "EAc8ar9by6s&list", category: "عبد الباسط عبد الصمد" },
    { id: "hcGGbkjPbZM&list", category: "عبد الباسط عبد الصمد" },
    { id: "NaG9YNZBtJw&list", category: "عبد الباسط عبد الصمد" },
    { id: "uGiNj2NAi9g&list", category: "عبد الباسط عبد الصمد" },
    { id: "fMBfhwQoC-s&list", category: "عبد الباسط عبد الصمد" },
    { id: "lmCh3k0qUQw&list", category: "عبد الباسط عبد الصمد" },
    { id: "cwBg6THSWwU&list", category: "عبد الباسط عبد الصمد" },
    { id: "IEoNmI2Nwr0&list", category: "عبد الباسط عبد الصمد" },
    { id: "RBFcYsFh6HI&list", category: "عبد الباسط عبد الصمد" },
    { id: "2e0IaJlbXCo&list", category: "عبد الباسط عبد الصمد" },
    { id: "RDen14w4Mkg&list", category: "عبد الباسط عبد الصمد" },
    { id: "nizicUjnN2E&list", category: "عبد الباسط عبد الصمد" },
    { id: "C0GDlU0twQw&list", category: "عبد الباسط عبد الصمد" },
    { id: "dMF-q_ZcVOo&list", category: "عبد الباسط عبد الصمد" },
    { id: "hS_E8dztTtQ&list", category: "عبد الباسط عبد الصمد" },
    { id: "wW6jGn45eek&list", category: "عبد الباسط عبد الصمد" },
    { id: "o5UBK33SxU0&list", category: "عبد الباسط عبد الصمد" },
    { id: "jRKh9Fvg7Y8&list", category: "عبد الباسط عبد الصمد" },
    { id: "rgn_7pc0Gok&list", category: "عبد الباسط عبد الصمد" },
    { id: "lPgJwIGjmHs&list", category: "عبد الباسط عبد الصمد" },
    { id: "Gi7jJuzgmY8&list", category: "عبد الباسط عبد الصمد" },
    { id: "HLCPLNv80Ys&list", category: "عبد الباسط عبد الصمد" },
    { id: "C33UFRUz--k&list", category: "عبد الباسط عبد الصمد" },
    { id: "nzo5xoVv_z8&list", category: "عبد الباسط عبد الصمد" },
    { id: "Rkfy1lwkIho&list", category: "عبد الباسط عبد الصمد" },
    { id: "kVqCvt5Ayp8&list", category: "عبد الباسط عبد الصمد" },
    { id: "EVhshWI9EWE&list", category: "عبد الباسط عبد الصمد" },
    { id: "o2DZpbYo24o&list", category: "عبد الباسط عبد الصمد" },
    { id: "dp09ZnQ1Kf4&list", category: "عبد الباسط عبد الصمد" },
    { id: "kD5YK-himIY&list", category: "عبد الباسط عبد الصمد" },
    { id: "I5fPfasaqE8&list", category: "عبد الباسط عبد الصمد" },
    { id: "5lmRF4H-VqU&list", category: "عبد الباسط عبد الصمد" },
    { id: "mHYVUrgU730&list", category: "عبد الباسط عبد الصمد" },
    { id: "wbltjyd0fP4&list", category: "عبد الباسط عبد الصمد" },
    { id: "iNP8GZHXZnc&list", category: "عبد الباسط عبد الصمد" },
    { id: "35qW_rYmg1Q&list", category: "عبد الباسط عبد الصمد" },
    { id: "sliDP-xoUQo&list", category: "عبد الباسط عبد الصمد" },
    { id: "Z4Uj5uslqIg&list", category: "عبد الباسط عبد الصمد" },
    { id: "jmJDLlFlkyU&list", category: "عبد الباسط عبد الصمد" },
    { id: "sUtXU4Wc1NI&list", category: "عبد الباسط عبد الصمد" },
    { id: "WSqKn1W-3wE&list", category: "عبد الباسط عبد الصمد" },
    { id: "tbKf8PJB0LY&list", category: "عبد الباسط عبد الصمد" },
    { id: "IWM7ydVkW1E&list", category: "عبد الباسط عبد الصمد" },
    { id: "8uBd3wuIJ0M&list", category: "عبد الباسط عبد الصمد" },
    { id: "mn0-0nK7AWw&list", category: "عبد الباسط عبد الصمد" },
    { id: "xAjk-SNkPew&list", category: "عبد الباسط عبد الصمد" },
    { id: "c3y9lpk4pa4&list", category: "عبد الباسط عبد الصمد" },
    { id: "lY8Z1CLvrc8&list", category: "عبد الباسط عبد الصمد" },
    { id: "taV2CUkKxpY&list", category: "عبد الباسط عبد الصمد" },
    { id: "ZB1qY-AS-sA&list", category: "عبد الباسط عبد الصمد" },
    { id: "wewQ1CKZeiE&list", category: "عبد الباسط عبد الصمد" },
    { id: "LVptgI1Astw&list", category: "عبد الباسط عبد الصمد" },
    { id: "uiaAcIrgivE&list", category: "عبد الباسط عبد الصمد" },
    { id: "tSkZcBBo87A&list", category: "عبد الباسط عبد الصمد" },
    { id: "VY0-iYdpl6Y&list", category: "عبد الباسط عبد الصمد" },
  ],
  "محمد صديق المنشاوي": [
    { id: "t0i9OKdmGj8&list", category: "محمد صديق المنشاوي" },
    { id: "enefZJLYprE&list", category: "محمد صديق المنشاوي" },
    { id: "xvFWLPwIpGQ&list", category: "محمد صديق المنشاوي" },
    { id: "4l8au17JOEM&list", category: "محمد صديق المنشاوي" },
    { id: "APUD2gnYv5E&list", category: "محمد صديق المنشاوي" },
    { id: "8-7q99FMxhM&list", category: "محمد صديق المنشاوي" },
    { id: "3jzGw99qAZo&list", category: "محمد صديق المنشاوي" },
    { id: "hSED1Hv_tDA&list", category: "محمد صديق المنشاوي" },
    { id: "htHpTYApEGg&list", category: "محمد صديق المنشاوي" },
    { id: "_xDx8wsxNq4&list", category: "محمد صديق المنشاوي" },
    { id: "OlB6rD7W8wA&list", category: "محمد صديق المنشاوي" },
    { id: "lyYMs0kPtQo&list", category: "محمد صديق المنشاوي" },
    { id: "LxIrg7c8EF8&list", category: "محمد صديق المنشاوي" },
    { id: "4pewPG-AkTA&list", category: "محمد صديق المنشاوي" },
    { id: "PsCSYHTeEjE&list", category: "محمد صديق المنشاوي" },
    { id: "RpRTnoCKztk&list", category: "محمد صديق المنشاوي" },
    { id: "hQlu5Z2ts7I&list", category: "محمد صديق المنشاوي" },
    { id: "q2CxLRCq6Ss&list", category: "محمد صديق المنشاوي" },
    { id: "FGz8EBLP9rc&list", category: "محمد صديق المنشاوي" },
    { id: "4Ua2sQ32Uf4&list", category: "محمد صديق المنشاوي" },
    { id: "I_MT0r3D4YY&list", category: "محمد صديق المنشاوي" },
    { id: "aTDdtQDjg6o&list", category: "محمد صديق المنشاوي" },
    { id: "LXjWdTRfxbU&list", category: "محمد صديق المنشاوي" },
    { id: "lLuf8SYAQnY&list", category: "محمد صديق المنشاوي" },
    { id: "AKPoUTNLuAM&list", category: "محمد صديق المنشاوي" },
    { id: "RbP0I2tTdok&list", category: "محمد صديق المنشاوي" },
    { id: "TRJPMqE2pog&list", category: "محمد صديق المنشاوي" },
    { id: "18Q2V6Fdtf0&list", category: "محمد صديق المنشاوي" },
    { id: "aEIJCTjO-lc&list", category: "محمد صديق المنشاوي" },
    { id: "Zm1y8L8RarU&list", category: "محمد صديق المنشاوي" },
    { id: "w_9-3SfvMF0&list", category: "محمد صديق المنشاوي" },
    { id: "3jLst9jy1lA&list", category: "محمد صديق المنشاوي" },
    { id: "PGslb1Fm80Q&list", category: "محمد صديق المنشاوي" },
    { id: "tkIhxYLykTA&list", category: "محمد صديق المنشاوي" },
    { id: "XLoNS-WjodQ&list", category: "محمد صديق المنشاوي" },
    { id: "oMXzKE2f7C8&list", category: "محمد صديق المنشاوي" },
    { id: "N0cYt1P_39w&list", category: "محمد صديق المنشاوي" },
    { id: "1cefkh7dR5o&list", category: "محمد صديق المنشاوي" },
    { id: "vhGlrkBmDmc&list", category: "محمد صديق المنشاوي" },
    { id: "Ezi4kI-37Jc&list", category: "محمد صديق المنشاوي" },
    { id: "Pbyui4T0Gnw&list", category: "محمد صديق المنشاوي" },
    { id: "MWJVoFzfO1I&list", category: "محمد صديق المنشاوي" },
    { id: "qLlf4DnaS4E&list", category: "محمد صديق المنشاوي" },
    { id: "kDtY3OR_ZO0&list", category: "محمد صديق المنشاوي" },
    { id: "Nqj6stpi12A&list", category: "محمد صديق المنشاوي" },
    { id: "-vH_Y8yZIjk&list", category: "محمد صديق المنشاوي" },
    { id: "cgc688I3FgQ&list", category: "محمد صديق المنشاوي" },
    { id: "z1zvVht1ItE&list", category: "محمد صديق المنشاوي" },
    { id: "9-MFOn0xq94&list", category: "محمد صديق المنشاوي" },
    { id: "Jlq4oWSqzB0&list", category: "محمد صديق المنشاوي" },
    { id: "wnLB2rt_hcU&list", category: "محمد صديق المنشاوي" },
    { id: "LtbyprvLXeU&list", category: "محمد صديق المنشاوي" },
    { id: "-Jy_6QlZk0g&list", category: "محمد صديق المنشاوي" },
    { id: "nH20ZRpU8X0&list", category: "محمد صديق المنشاوي" },
    { id: "8zlQmUUXR_c&list", category: "محمد صديق المنشاوي" },
    { id: "UjzYArHIdk8&list", category: "محمد صديق المنشاوي" },
    { id: "ckIPE0DFmUs&list", category: "محمد صديق المنشاوي" },
    { id: "q_s4M4vGJwM&list", category: "محمد صديق المنشاوي" },
    { id: "wQwCmuhhLMo&list", category: "محمد صديق المنشاوي" },
    { id: "aXAacOg_gOc&list", category: "محمد صديق المنشاوي" },
    { id: "IEjYCVFzSwY&list", category: "محمد صديق المنشاوي" },
    { id: "hXyN01B18ZA&list", category: "محمد صديق المنشاوي" },
    { id: "8o-MTyrjZNw&list", category: "محمد صديق المنشاوي" },
    { id: "18UqSrtlVaQ&list", category: "محمد صديق المنشاوي" },
    { id: "_WsBrxbCORA&list", category: "محمد صديق المنشاوي" },
    { id: "lccMS_rdKD0&list", category: "محمد صديق المنشاوي" },
    { id: "5e3mR2m2mIM&list", category: "محمد صديق المنشاوي" },
    { id: "peRf06tL8PQ&list", category: "محمد صديق المنشاوي" },
    { id: "UUe5nYxHpOA&list", category: "محمد صديق المنشاوي" },
    { id: "PB4uA9KgGCs&list", category: "محمد صديق المنشاوي" },
    { id: "8sWFV5Wu5qc&list", category: "محمد صديق المنشاوي" },
    { id: "A8zUmmxTo1U&list", category: "محمد صديق المنشاوي" },
    { id: "_SW9ywITFVE&list", category: "محمد صديق المنشاوي" },
    { id: "gG9MEf2eAZo&list", category: "محمد صديق المنشاوي" },
    { id: "MrTRnuzmBIU&list", category: "محمد صديق المنشاوي" },
    { id: "YpNoWWFbEKo&list", category: "محمد صديق المنشاوي" },
    { id: "h3zfbloPOPg&list", category: "محمد صديق المنشاوي" },
    { id: "00GMQlK3jEo&list", category: "محمد صديق المنشاوي" },
    { id: "JAd3KS-m6Qc&list", category: "محمد صديق المنشاوي" },
    { id: "vCF4DKlvF4Q&list", category: "محمد صديق المنشاوي" },
    { id: "UpN-3U84gtg&list", category: "محمد صديق المنشاوي" },
    { id: "hqMghEjcsHQ&list", category: "محمد صديق المنشاوي" },
    { id: "yHbZZ05VliE&list", category: "محمد صديق المنشاوي" },
    { id: "Xpp8Jh1OO-o&list", category: "محمد صديق المنشاوي" },
    { id: "uCeFEDYTTCA&list", category: "محمد صديق المنشاوي" },
    { id: "P3luj8bMGVg&list", category: "محمد صديق المنشاوي" },
    { id: "tTtJs2_hIQM&list", category: "محمد صديق المنشاوي" },
    { id: "DrLK7tgP170&list", category: "محمد صديق المنشاوي" },
    { id: "CsNQjvBPAKo&list", category: "محمد صديق المنشاوي" },
    { id: "gj7RdvhYmn8&list", category: "محمد صديق المنشاوي" },
    { id: "D1BBOkz2zwA&list", category: "محمد صديق المنشاوي" },
    { id: "PWCIusfx26M&list", category: "محمد صديق المنشاوي" },
    { id: "aBLELLmwdq4&list", category: "محمد صديق المنشاوي" },
    { id: "rgZizGNBQEo&list", category: "محمد صديق المنشاوي" },
    { id: "EY__ZQDdHPE&list", category: "محمد صديق المنشاوي" },
    { id: "EJqOPfDnZxE&list", category: "محمد صديق المنشاوي" },
    { id: "p5sOdIoz3Us&list", category: "محمد صديق المنشاوي" },
    { id: "Qzd41G2H5qs&list", category: "محمد صديق المنشاوي" },
    { id: "UQi0TPRO2Ns&list", category: "محمد صديق المنشاوي" },
    { id: "gJ5ODTASB_M&list", category: "محمد صديق المنشاوي" },
    { id: "F9bq0mrG0F0&list", category: "محمد صديق المنشاوي" },
    { id: "K06PmUpsf2w&list", category: "محمد صديق المنشاوي" },
    { id: "uaC2b_qtOK8&list", category: "محمد صديق المنشاوي" },
    { id: "e9xKcGoydbs&list", category: "محمد صديق المنشاوي" },
    { id: "TD_ii4BhVgo&list", category: "محمد صديق المنشاوي" },
    { id: "Rq-08cPRh3M&list", category: "محمد صديق المنشاوي" },
    { id: "5cf4oANSeUg&list", category: "محمد صديق المنشاوي" },
    { id: "2ypcso7pUTs&list", category: "محمد صديق المنشاوي" },
    { id: "pNVtXbhytwk&list", category: "محمد صديق المنشاوي" },
    { id: "1Ptit6DkV4E&list", category: "محمد صديق المنشاوي" },
    { id: "ARRqzwVQ2kM&list", category: "محمد صديق المنشاوي" },
    { id: "h13qthyo0d8&list", category: "محمد صديق المنشاوي" },
    { id: "F1pIhOXC9LU&list", category: "محمد صديق المنشاوي" },
    { id: "2dnjqVjD13w&list", category: "محمد صديق المنشاوي" },
  ],
  "ماهر المعيقلي": [
    { id: "DBE5asBt5cc&list", category: "ماهر المعيقلي" },
    { id: "LCXRCVV75-o&list", category: "ماهر المعيقلي" },
    { id: "cKcz51ras7k&list", category: "ماهر المعيقلي" },
    { id: "C4NrEWyOXB0&list", category: "ماهر المعيقلي" },
    { id: "rLhpI-s6YqM&list", category: "ماهر المعيقلي" },
    { id: "fGO0rs5WGdU&list", category: "ماهر المعيقلي" },
    { id: "BHxQH5qGWVE&list", category: "ماهر المعيقلي" },
    { id: "dKt6jhc_znk&list", category: "ماهر المعيقلي" },
    { id: "UbmPCeCzlqk&list", category: "ماهر المعيقلي" },
    { id: "ABQf_4yWjXE&list", category: "ماهر المعيقلي" },
    { id: "Ik9qGm0YaFo&list", category: "ماهر المعيقلي" },
    { id: "TMUEYYf-h0I&list", category: "ماهر المعيقلي" },
    { id: "rOY6VPnDea8&list", category: "ماهر المعيقلي" },
    { id: "VSf5GCGK-2k&list", category: "ماهر المعيقلي" },
    { id: "oFbRggaEiK4&list", category: "ماهر المعيقلي" },
    { id: "Pkp3VxpLRtw&list", category: "ماهر المعيقلي" },
    { id: "k_ogNob8BeM&list", category: "ماهر المعيقلي" },
    { id: "fc-4ULXLJig&list", category: "ماهر المعيقلي" },
    { id: "hdbdfTwFbHQ&list", category: "ماهر المعيقلي" },
    { id: "TAidJ_sUFxo&list", category: "ماهر المعيقلي" },
    { id: "GR_3WeJusdM&list", category: "ماهر المعيقلي" },
    { id: "uOfR_LECIEU&list", category: "ماهر المعيقلي" },
    { id: "DZloEK1pS6o&list", category: "ماهر المعيقلي" },
    { id: "VKLTKF2ffck&list", category: "ماهر المعيقلي" },
    { id: "ElP436waD4Q&list", category: "ماهر المعيقلي" },
    { id: "DyJ5knxYq_g&list", category: "ماهر المعيقلي" },
    { id: "60sqFEYFe5s&list", category: "ماهر المعيقلي" },
    { id: "O947hxdRjdQ&list", category: "ماهر المعيقلي" },
    { id: "TJdCSePdNlk&list", category: "ماهر المعيقلي" },
    { id: "8xcYfTFu1_k&list", category: "ماهر المعيقلي" },
    { id: "yaBeDctIEtE&list", category: "ماهر المعيقلي" },
    { id: "4IWvCDF5s7k&list", category: "ماهر المعيقلي" },
    { id: "eu-oVKV7EDQ&list", category: "ماهر المعيقلي" },
    { id: "iHqrTudTWAk&list", category: "ماهر المعيقلي" },
    { id: "f5jjy1Dunhc&list", category: "ماهر المعيقلي" },
    { id: "YbmJwka9E08&list", category: "ماهر المعيقلي" },
    { id: "SaZpaL4eD00&list", category: "ماهر المعيقلي" },
    { id: "0JIC3IoZI_I&list", category: "ماهر المعيقلي" },
    { id: "R0le_Kw5LG0&list", category: "ماهر المعيقلي" },
    { id: "IiAD68e8Kjc&list", category: "ماهر المعيقلي" },
    { id: "pCbWvpUxz9E&list", category: "ماهر المعيقلي" },
    { id: "rtBYm4EFPl8&list", category: "ماهر المعيقلي" },
    { id: "3ceehDNLNgM&list", category: "ماهر المعيقلي" },
    { id: "ozPeXYLbvts&list", category: "ماهر المعيقلي" },
    { id: "KWItd7Ndan8&list", category: "ماهر المعيقلي" },
    { id: "pmdWLBsmusA&list", category: "ماهر المعيقلي" },
    { id: "_ufyq8jczjU&list", category: "ماهر المعيقلي" },
    { id: "tFs6D2yMDQA&list", category: "ماهر المعيقلي" },
    { id: "tG8G1V8OAl8&list", category: "ماهر المعيقلي" },
    { id: "nFya8lhMozA&list", category: "ماهر المعيقلي" },
    { id: "bsb0m9M_rP8&list", category: "ماهر المعيقلي" },
    { id: "qg4WbL8yFE4&list", category: "ماهر المعيقلي" },
    { id: "WfAh-5J-X4w&list", category: "ماهر المعيقلي" },
    { id: "YtJvK442tvE&list", category: "ماهر المعيقلي" },
    { id: "deEOhzqoRh4&list", category: "ماهر المعيقلي" },
    { id: "dXsaI8fx_eU&list", category: "ماهر المعيقلي" },
    { id: "f5Gc3QtEwrE&list", category: "ماهر المعيقلي" },
    { id: "OeyHXjdEQ5s&list", category: "ماهر المعيقلي" },
    { id: "u-Ctvn2Bjjo&list", category: "ماهر المعيقلي" },
    { id: "wY0swHDj8yk&list", category: "ماهر المعيقلي" },
    { id: "banU8DF-NZY&list", category: "ماهر المعيقلي" },
    { id: "T9l4Nr-6WQo&list", category: "ماهر المعيقلي" },
    { id: "pr5Ykr5RBIg&list", category: "ماهر المعيقلي" },
    { id: "_pgFNqRue28&list", category: "ماهر المعيقلي" },
    { id: "pMFClpiB5ng&list", category: "ماهر المعيقلي" },
    { id: "h_85n1Q6V3M&list", category: "ماهر المعيقلي" },
    { id: "-R8Lvgm2DLM&list", category: "ماهر المعيقلي" },
    { id: "6XKAkj-mNTk&list", category: "ماهر المعيقلي" },
    { id: "e3QDKN_Nc_I&list", category: "ماهر المعيقلي" },
    { id: "RwK-Pl7lJzs&list", category: "ماهر المعيقلي" },
    { id: "m9RolPJZGWg&list", category: "ماهر المعيقلي" },
    { id: "_iXP9Lst48M&list", category: "ماهر المعيقلي" },
    { id: "906pq4-XxV0&list", category: "ماهر المعيقلي" },
    { id: "CZ6ejCNDR_o&list", category: "ماهر المعيقلي" },
    { id: "zJ7by5m7Np8&list", category: "ماهر المعيقلي" },
    { id: "cP__iEXwTIY&list", category: "ماهر المعيقلي" },
    { id: "ricqnm3Ww00&list", category: "ماهر المعيقلي" },
    { id: "UtrTpVuw8U8&list", category: "ماهر المعيقلي" },
    { id: "JvUj4NRJumg&list", category: "ماهر المعيقلي" },
    { id: "YnC7V_fd6w4&list", category: "ماهر المعيقلي" },
    { id: "1IvQeFeeR6E&list", category: "ماهر المعيقلي" },
    { id: "_Ht2k6lXsC4&list", category: "ماهر المعيقلي" },
    { id: "WP139F6lbmU&list", category: "ماهر المعيقلي" },
    { id: "fCeGjEgfrYM&list", category: "ماهر المعيقلي" },
    { id: "v0wtdiMlCek&list", category: "ماهر المعيقلي" },
    { id: "Tj5pOsSEmEY&list", category: "ماهر المعيقلي" },
    { id: "POVCpLsWwEg&list", category: "ماهر المعيقلي" },
    { id: "6n6bLOf2iQo&list", category: "ماهر المعيقلي" },
    { id: "S_d5-BJZbE8&list", category: "ماهر المعيقلي" },
    { id: "xW96pUogkgs&list", category: "ماهر المعيقلي" },
    { id: "CV85hHprNAQ&list", category: "ماهر المعيقلي" },
    { id: "C8bQiXMEtiY&list", category: "ماهر المعيقلي" },
    { id: "qnQ3yiqlWA8&list", category: "ماهر المعيقلي" },
    { id: "kCxdBaW4UaI&list", category: "ماهر المعيقلي" },
    { id: "xuH2Jwn1YNU&list", category: "ماهر المعيقلي" },
    { id: "b2gFoUEMRPs&list", category: "ماهر المعيقلي" },
    { id: "srPfm-WX0x8&list", category: "ماهر المعيقلي" },
    { id: "j7IpX9DvxE0&list", category: "ماهر المعيقلي" },
    { id: "hlIQyM48BPs&list", category: "ماهر المعيقلي" },
    { id: "4HuOzezeAhI&list", category: "ماهر المعيقلي" },
    { id: "ReHs4bdJ5l4&list", category: "ماهر المعيقلي" },
    { id: "AvA2B8oxGQ4&list", category: "ماهر المعيقلي" },
    { id: "3xgMgmlkY_s&list", category: "ماهر المعيقلي" },
    { id: "jb9fny6aXqQ&list", category: "ماهر المعيقلي" },
    { id: "N8rAJcLZQXk&list", category: "ماهر المعيقلي" },
    { id: "k79p-aGtN40&list", category: "ماهر المعيقلي" },
    { id: "b_BxoDKJ9Cg&list", category: "ماهر المعيقلي" },
    { id: "4lGGGGttlKE&list", category: "ماهر المعيقلي" },
    { id: "4Teok2IvftM&list", category: "ماهر المعيقلي" },
    { id: "-fJjsPpDGZA&list", category: "ماهر المعيقلي" },
    { id: "NiuoqOS5euc&list", category: "ماهر المعيقلي" },
    { id: "seRCCpWG-3s&list", category: "ماهر المعيقلي" },
    { id: "z-OrsuU75OU&list", category: "ماهر المعيقلي" },
    { id: "0OuSb7lWhe8&list", category: "ماهر المعيقلي" },
  ],
  "سعد الغامدي": [
    { id: "FXowl7Kak5I&list", category: "سعد الغامدي" },
    { id: "8PZYGAVrOb8&list", category: "سعد الغامدي" },
    { id: "8FOO6kIUTas&list", category: "سعد الغامدي" },
    { id: "MEXC3hJl3_w&list", category: "سعد الغامدي" },
    { id: "o8kSnp9xIHY&list", category: "سعد الغامدي" },
    { id: "iynjPh1HoYE&list", category: "سعد الغامدي" },
    { id: "mNGBXxpbvuA&list", category: "سعد الغامدي" },
    { id: "u1_oY961eos&list", category: "سعد الغامدي" },
    { id: "Ta8YqVXRoOI&list", category: "سعد الغامدي" },
    { id: "Hl9qdMfACXk&list", category: "سعد الغامدي" },
    { id: "rnh9GGdMDBk&list", category: "سعد الغامدي" },
    { id: "Fk9y1MoHye0&list", category: "سعد الغامدي" },
    { id: "MToAjhRaq6Q&list", category: "سعد الغامدي" },
    { id: "Rz8j-pf0mGs&list", category: "سعد الغامدي" },
    { id: "tpEJZoN6Ybg&list", category: "سعد الغامدي" },
    { id: "ZdZKknsblzc&list", category: "سعد الغامدي" },
    { id: "CJxJw4ITjLQ&list", category: "سعد الغامدي" },
    { id: "zJe1xImfN7I&list", category: "سعد الغامدي" },
    { id: "-WjrHdrNe1M&list", category: "سعد الغامدي" },
    { id: "5f1gw7G1NIs&list", category: "سعد الغامدي" },
    { id: "LLmWl59gQ64&list", category: "سعد الغامدي" },
    { id: "LoO-l_Z0B-U&list", category: "سعد الغامدي" },
    { id: "u7Zn-oNQLsU&list", category: "سعد الغامدي" },
    { id: "RElAYOETnU0&list", category: "سعد الغامدي" },
    { id: "x1BXWHQAeB0&list", category: "سعد الغامدي" },
    { id: "CgdA-8DPpQY&list", category: "سعد الغامدي" },
    { id: "Isneuw-_Euc&list", category: "سعد الغامدي" },
    { id: "dfhxZVjuzl8&list", category: "سعد الغامدي" },
    { id: "1BZsVpV6zgs&list", category: "سعد الغامدي" },
    { id: "YGdGknngQ2A&list", category: "سعد الغامدي" },
    { id: "BxnbNmXtCbM&list", category: "سعد الغامدي" },
    { id: "7c9K-Sg-Y_k&list", category: "سعد الغامدي" },
    { id: "FEnQ9KG4VDU&list", category: "سعد الغامدي" },
    { id: "1T45qX-Qrw8&list", category: "سعد الغامدي" },
    { id: "FfxQhdpzJI8&list", category: "سعد الغامدي" },
    { id: "f-FR8fWWLRk&list", category: "سعد الغامدي" },
    { id: "XhBndG1E30o&list", category: "سعد الغامدي" },
    { id: "mEJk4Ycj4xA&list", category: "سعد الغامدي" },
    { id: "bCZRsy8l6Pw&list", category: "سعد الغامدي" },
    { id: "KnXFfBs3300&list", category: "سعد الغامدي" },
    { id: "iz7W3X3K3wc&list", category: "سعد الغامدي" },
    { id: "7cbuHW0OlUY&list", category: "سعد الغامدي" },
    { id: "BqAEsbhTdPw&list", category: "سعد الغامدي" },
    { id: "VX-pdZxbEbM&list", category: "سعد الغامدي" },
    { id: "4TVQtVAsbmc&list", category: "سعد الغامدي" },
    { id: "LANFYuWta50&list", category: "سعد الغامدي" },
    { id: "fS3n8rkSDzE&list", category: "سعد الغامدي" },
    { id: "XGm0gvgDrNI&list", category: "سعد الغامدي" },
    { id: "5VRdDD8C540&list", category: "سعد الغامدي" },
    { id: "uCm8kf8Ohck&list", category: "سعد الغامدي" },
    { id: "1M6Qc5h7l28&list", category: "سعد الغامدي" },
    { id: "YtPuQ6IFC2M&list", category: "سعد الغامدي" },
    { id: "MsdxCim7glU&list", category: "سعد الغامدي" },
    { id: "PuaWhTDwoQ8&list", category: "سعد الغامدي" },
    { id: "Fm8qXFsUvBY&list", category: "سعد الغامدي" },
    { id: "NgHGk0RlNwk&list", category: "سعد الغامدي" },
    { id: "N8gXI9Awn0U&list", category: "سعد الغامدي" },
    { id: "bPjS6K0WZd8&list", category: "سعد الغامدي" },
    { id: "BmK6p3ZIink&list", category: "سعد الغامدي" },
    { id: "d1GwhRxQzOY&list", category: "سعد الغامدي" },
    { id: "Q6xhOkT9NtA&list", category: "سعد الغامدي" },
    { id: "ptYpFhzAasE&list", category: "سعد الغامدي" },
    { id: "7m_yQYz0eMo&list", category: "سعد الغامدي" },
    { id: "xavX4zRXsK8&list", category: "سعد الغامدي" },
    { id: "hCZn-QYTfbU&list", category: "سعد الغامدي" },
    { id: "8lpBzCUiSXQ&list", category: "سعد الغامدي" },
    { id: "rbEV6_QTTBM&list", category: "سعد الغامدي" },
    { id: "CQmRL4mKEC8&list", category: "سعد الغامدي" },
    { id: "KSWKZ-neX6I&list", category: "سعد الغامدي" },
    { id: "8bsPdtFqTlQ&list", category: "سعد الغامدي" },
    { id: "GX4cOkLCcLI&list", category: "سعد الغامدي" },
    { id: "Siwq_P-gXXI&list", category: "سعد الغامدي" },
    { id: "bIDkp3-RODc&list", category: "سعد الغامدي" },
    { id: "rQklRaj5BHw&list", category: "سعد الغامدي" },
    { id: "DG_aqEeoLmA&list", category: "سعد الغامدي" },
    { id: "l-rPKfTo7HM&list", category: "سعد الغامدي" },
    { id: "JfCBRJK4Qt0&list", category: "سعد الغامدي" },
    { id: "u42c8EjYaoE&list", category: "سعد الغامدي" },
    { id: "EU90r8lWTvc&list", category: "سعد الغامدي" },
    { id: "c2W_FwZxk50&list", category: "سعد الغامدي" },
    { id: "Xcg_uMYd8Bk&list", category: "سعد الغامدي" },
    { id: "cexwwCAcggc&list", category: "سعد الغامدي" },
    { id: "9p9SpPX8Itg&list", category: "سعد الغامدي" },
    { id: "sqViJO4zyps&list", category: "سعد الغامدي" },
    { id: "dXMDQbtpXdM&list", category: "سعد الغامدي" },
    { id: "w6mNN6i42dQ&list", category: "سعد الغامدي" },
    { id: "D1ibESyE80U&list", category: "سعد الغامدي" },
    { id: "AOGmvKLUNdk&list", category: "سعد الغامدي" },
    { id: "gAm7AxaMuVA&list", category: "سعد الغامدي" },
    { id: "VhHwdIU6D7Y&list", category: "سعد الغامدي" },
    { id: "W_uYGpWoykg&list", category: "سعد الغامدي" },
    { id: "FeX22yqn2gQ&list", category: "سعد الغامدي" },
    { id: "fS50wBN6g68&list", category: "سعد الغامدي" },
    { id: "LwOpIzX1ucM&list", category: "سعد الغامدي" },
    { id: "Ts7eK83N8BA&list", category: "سعد الغامدي" },
    { id: "b-Fwwf8nvWM&list", category: "سعد الغامدي" },
    { id: "JUva-CLszug&list", category: "سعد الغامدي" },
    { id: "K6v6eSTVtjQ&list", category: "سعد الغامدي" },
    { id: "ruSsKMXTgwM&list", category: "سعد الغامدي" },
    { id: "tNKa5dDbWTI&list", category: "سعد الغامدي" },
    { id: "zBvIvvjItbo&list", category: "سعد الغامدي" },
    { id: "juhtWNGRPqI&list", category: "سعد الغامدي" },
    { id: "Z8IM8yu_LL8&list", category: "سعد الغامدي" },
    { id: "kL5jPb6hTQY&list", category: "سعد الغامدي" },
    { id: "75YRX6wDv_Y&list", category: "سعد الغامدي" },
    { id: "7BvGjJqo7a4&list", category: "سعد الغامدي" },
    { id: "IGxDzsY1PsY&list", category: "سعد الغامدي" },
    { id: "MUGc4eIjrfA&list", category: "سعد الغامدي" },
    { id: "X-OtLzewhzo&list", category: "سعد الغامدي" },
    { id: "ZsCHIG8wbbs&list", category: "سعد الغامدي" },
    { id: "YnsnYO7_sa8&list", category: "سعد الغامدي" },
    { id: "6lDyMpMEU5M&list", category: "سعد الغامدي" },
    { id: "NEm93O-iT_k&list", category: "سعد الغامدي" },
    { id: "Dni8F4nEt4Y&list", category: "سعد الغامدي" },
  ],
  "أحمد العجمي": [
    { id: "QdXxT_KLJjk&list", category: "أحمد العجمي" },
    { id: "Q5kAtUGxCkc&list", category: "أحمد العجمي" },
    { id: "Z2Xi0ChjJe4&list", category: "أحمد العجمي" },
    { id: "1AzZMmJZk3M&list", category: "أحمد العجمي" },
    { id: "6TJe5wp3gXI&list", category: "أحمد العجمي" },
    { id: "UwxsqVUA7Z0&list", category: "أحمد العجمي" },
    { id: "vIsc9X8j1Ys&list", category: "أحمد العجمي" },
    { id: "cFIrXi13iFc&list", category: "أحمد العجمي" },
    { id: "O27lHmNnfy4&list", category: "أحمد العجمي" },
    { id: "b1JMHGGLIPU&list", category: "أحمد العجمي" },
    { id: "D3rJ7STA0O0&list", category: "أحمد العجمي" },
    { id: "MDq434h4AOk&list", category: "أحمد العجمي" },
    { id: "TXqDDsKlBhg&list", category: "أحمد العجمي" },
    { id: "--d7sKrMN6M&list", category: "أحمد العجمي" },
    { id: "z65VHt54Ufs&list", category: "أحمد العجمي" },
    { id: "1hjkir26a5E&list", category: "أحمد العجمي" },
    { id: "8hzKqOoeuYE&list", category: "أحمد العجمي" },
    { id: "a3aAMG5t3zY&list", category: "أحمد العجمي" },
    { id: "U56CSxqpkEA&list", category: "أحمد العجمي" },
    { id: "0RS6XsHbuaU&list", category: "أحمد العجمي" },
    { id: "eLJxK_BSF9Y&list", category: "أحمد العجمي" },
    { id: "X11vs1D5mLc&list", category: "أحمد العجمي" },
    { id: "mJd_AyFqwZI&list", category: "أحمد العجمي" },
    { id: "3ODt5H7_7aM&list", category: "أحمد العجمي" },
    { id: "hefmOh955bc&list", category: "أحمد العجمي" },
    { id: "yX6w9xXcunY&list", category: "أحمد العجمي" },
    { id: "CWMJLSHBCsw&list", category: "أحمد العجمي" },
    { id: "4GkLd2miER4&list", category: "أحمد العجمي" },
    { id: "iGJsMSh3Frs&list", category: "أحمد العجمي" },
    { id: "Yv5pY4JOCpc&list", category: "أحمد العجمي" },
    { id: "TA8I9ZzLTnY&list", category: "أحمد العجمي" },
    { id: "OsAPjlgH80k&list", category: "أحمد العجمي" },
    { id: "ct_YTAB0hQU&list", category: "أحمد العجمي" },
    { id: "y_qCOpTCWGY&list", category: "أحمد العجمي" },
    { id: "tqwwHtT0DVU&list", category: "أحمد العجمي" },
    { id: "eNWBTmmlwcA&list", category: "أحمد العجمي" },
    { id: "aBmsoR4OdQU&list", category: "أحمد العجمي" },
    { id: "US38R5WdMzI&list", category: "أحمد العجمي" },
    { id: "CuRGWwD-qIw&list", category: "أحمد العجمي" },
    { id: "xfpV6_t7po8&list", category: "أحمد العجمي" },
    { id: "W_adhAo7Lr8&list", category: "أحمد العجمي" },
    { id: "Y6rZUZRY-xk&list", category: "أحمد العجمي" },
    { id: "ABCuk2RStv8&list", category: "أحمد العجمي" },
    { id: "RW1nt0y2a30&list", category: "أحمد العجمي" },
    { id: "baTjFpS4Ji8&list", category: "أحمد العجمي" },
    { id: "8-m-AZYE0sY&list", category: "أحمد العجمي" },
    { id: "ugF54I5tuEc&list", category: "أحمد العجمي" },
    { id: "CZv-o_HkRh0&list", category: "أحمد العجمي" },
    { id: "x0ATKwVbAgA&list", category: "أحمد العجمي" },
    { id: "vPU5HjGoTCQ&list", category: "أحمد العجمي" },
    { id: "R9bvGKep2cA&list", category: "أحمد العجمي" },
    { id: "Xu3Jvl6C4lY&list", category: "أحمد العجمي" },
    { id: "hsrzAxQQMTY&list", category: "أحمد العجمي" },
    { id: "gfy1XFJ-v9w&list", category: "أحمد العجمي" },
    { id: "lP8n2SdBcBE&list", category: "أحمد العجمي" },
    { id: "h8LuPhBAPyU&list", category: "أحمد العجمي" },
    { id: "ddO97DARdT8&list", category: "أحمد العجمي" },
    { id: "a_Evr-b3g7Q&list", category: "أحمد العجمي" },
    { id: "UrnD5iJy7LU&list", category: "أحمد العجمي" },
    { id: "Y1_aewfLnM4&list", category: "أحمد العجمي" },
    { id: "XKT3_iUEzRk&list", category: "أحمد العجمي" },
    { id: "aJsUP3Lqafc&list", category: "أحمد العجمي" },
    { id: "OEndaOIo6r4&list", category: "أحمد العجمي" },
    { id: "M9mUxIxComI&list", category: "أحمد العجمي" },
    { id: "FDK1MMlrlE8&list", category: "أحمد العجمي" },
    { id: "Tx9cFQt-PoU&list", category: "أحمد العجمي" },
    { id: "txpp1rYBRYA&list", category: "أحمد العجمي" },
    { id: "Lx3ytbOyw6s&list", category: "أحمد العجمي" },
    { id: "_JxhD3MNh7k&list", category: "أحمد العجمي" },
    { id: "ebbGM12Y_WY&list", category: "أحمد العجمي" },
    { id: "o3gfxpyBmSI&list", category: "أحمد العجمي" },
    { id: "UeUZ10RBP_E&list", category: "أحمد العجمي" },
    { id: "3X-ies1thdU&list", category: "أحمد العجمي" },
    { id: "pK6_Wf2Z3Yc&list", category: "أحمد العجمي" },
    { id: "97knCaDLPhk&list", category: "أحمد العجمي" },
    { id: "UslgQ6yjAJQ&list", category: "أحمد العجمي" },
    { id: "52loVuf7bQo&list", category: "أحمد العجمي" },
    { id: "XcVwwo5kLGg&list", category: "أحمد العجمي" },
    { id: "yOAxHS9QMac&list", category: "أحمد العجمي" },
    { id: "aHqRmjo3a_A&list", category: "أحمد العجمي" },
    { id: "l1-wp0Sclg4&list", category: "أحمد العجمي" },
    { id: "utXelgrF9Ho&list", category: "أحمد العجمي" },
    { id: "6cKjL-BUBIA&list", category: "أحمد العجمي" },
    { id: "pOG7N9uTTn8&list", category: "أحمد العجمي" },
    { id: "DFr_2GsfJJE&list", category: "أحمد العجمي" },
    { id: "Msss97ZGmfk&list", category: "أحمد العجمي" },
    { id: "RypEZoASbyc&list", category: "أحمد العجمي" },
    { id: "LHDQxJuik1Q&list", category: "أحمد العجمي" },
    { id: "geVewg1hwwo&list", category: "أحمد العجمي" },
    { id: "tnPzMnU0U1I&list", category: "أحمد العجمي" },
    { id: "OVokpIYN8yo&list", category: "أحمد العجمي" },
    { id: "Elp0KB7r-ZA&list", category: "أحمد العجمي" },
    { id: "A8nqN2vrL3g&list", category: "أحمد العجمي" },
    { id: "0Y_ogKm1Jmc&list", category: "أحمد العجمي" },
    { id: "YaVLvcOqeiI&list", category: "أحمد العجمي" },
    { id: "fQlAJjMCKGo&list", category: "أحمد العجمي" },
    { id: "3VUO6Dr2orY&list", category: "أحمد العجمي" },
    { id: "hA5Fh5HBluY&list", category: "أحمد العجمي" },
    { id: "xGIXWqZICac&list", category: "أحمد العجمي" },
    { id: "2UTN2C6JZ-M&list", category: "أحمد العجمي" },
    { id: "IvWX7jKnHuM&list", category: "أحمد العجمي" },
    { id: "GrUi-e7ovfo&list", category: "أحمد العجمي" },
    { id: "1MpQOpepx9k&list", category: "أحمد العجمي" },
    { id: "zM2TzLy5Ne8&list", category: "أحمد العجمي" },
    { id: "7rW706zp4O8&list", category: "أحمد العجمي" },
    { id: "vVBxFTXK05w&list", category: "أحمد العجمي" },
    { id: "HERCb6nOfoU&list", category: "أحمد العجمي" },
    { id: "HrtahfOkE-8&list", category: "أحمد العجمي" },
    { id: "FzkrSbjCuAs&list", category: "أحمد العجمي" },
    { id: "u5FO0gPWdEI&list", category: "أحمد العجمي" },
    { id: "6PzCzQKcP-0&list", category: "أحمد العجمي" },
    { id: "FbDKZ_l6loU&list", category: "أحمد العجمي" },
    { id: "X5hg9oSR_00&list", category: "أحمد العجمي" },
  ],
  "عبد الرحمن السديس": [
    { id: "kb9_X4_ky5s&list", category: "عبد الرحمن السديس" },
    { id: "od45Xd3zjKA&list", category: "عبد الرحمن السديس" },
    { id: "_2oZD_70eMk&list", category: "عبد الرحمن السديس" },
    { id: "nyjGzxe30RM&list", category: "عبد الرحمن السديس" },
    { id: "W3Nww4HHWao&list", category: "عبد الرحمن السديس" },
    { id: "9j4BiO4TQFk&list", category: "عبد الرحمن السديس" },
    { id: "yy5Ae7zq3Pc&list", category: "عبد الرحمن السديس" },
    { id: "P6ype0sWP2Y&list", category: "عبد الرحمن السديس" },
    { id: "flW_NHy5ftY&list", category: "عبد الرحمن السديس" },
    { id: "OPlgQVkObAc&list", category: "عبد الرحمن السديس" },
    { id: "DMNJxoijPTE&list", category: "عبد الرحمن السديس" },
    { id: "scwzlZdRB1o&list", category: "عبد الرحمن السديس" },
    { id: "u5S-wwRHIO8&list", category: "عبد الرحمن السديس" },
    { id: "3rFqwOXU9Cw&list", category: "عبد الرحمن السديس" },
    { id: "ZU6uuu3bh1Q&list", category: "عبد الرحمن السديس" },
    { id: "kFKCikSWx-A&list", category: "عبد الرحمن السديس" },
    { id: "60zrDziSvVA&list", category: "عبد الرحمن السديس" },
    { id: "cHaNiFM5d7s&list", category: "عبد الرحمن السديس" },
    { id: "iAKe9OKYNps&list", category: "عبد الرحمن السديس" },
    { id: "Sx8rJ1yyXn4&list", category: "عبد الرحمن السديس" },
    { id: "oPEWM4-Qu0I&list", category: "عبد الرحمن السديس" },
    { id: "d9IC3jvmymI&list", category: "عبد الرحمن السديس" },
    { id: "Syri76gIkhs&list", category: "عبد الرحمن السديس" },
    { id: "Xs35tTRl5aM&list", category: "عبد الرحمن السديس" },
    { id: "k3-rX7N0W_g&list", category: "عبد الرحمن السديس" },
    { id: "t4Ul80j0LWA&list", category: "عبد الرحمن السديس" },
    { id: "BSDuFV2G9YY&list", category: "عبد الرحمن السديس" },
    { id: "JbJK9Hudo2U&list", category: "عبد الرحمن السديس" },
    { id: "WvO0eG-D3KM&list", category: "عبد الرحمن السديس" },
    { id: "7Ko4N4KbgRo&list", category: "عبد الرحمن السديس" },
    { id: "H8A9nj3tk10&list", category: "عبد الرحمن السديس" },
    { id: "X38RZ5D7cmM&list", category: "عبد الرحمن السديس" },
    { id: "4IGYnVctMk8&list", category: "عبد الرحمن السديس" },
    { id: "M2d_7giyVPg&list", category: "عبد الرحمن السديس" },
    { id: "awXjC0L1uzQ&list", category: "عبد الرحمن السديس" },
    { id: "nIk2Y2SKIcA&list", category: "عبد الرحمن السديس" },
    { id: "QYB_O9fOYi4&list", category: "عبد الرحمن السديس" },
    { id: "jy8hqLAUWKA&list", category: "عبد الرحمن السديس" },
    { id: "Mi6P22YPEqc&list", category: "عبد الرحمن السديس" },
    { id: "7Y3EAukKoYI&list", category: "عبد الرحمن السديس" },
    { id: "UaDyeEqEIs8&list", category: "عبد الرحمن السديس" },
    { id: "4hCUu4I9jPU&list", category: "عبد الرحمن السديس" },
    { id: "rHfzIJi36YU&list", category: "عبد الرحمن السديس" },
    { id: "9h-pOBUahYQ&list", category: "عبد الرحمن السديس" },
    { id: "324fpNsfQLQ&list", category: "عبد الرحمن السديس" },
    { id: "CMA27sVGvdE&list", category: "عبد الرحمن السديس" },
    { id: "-EtMR9Uvc5M&list", category: "عبد الرحمن السديس" },
    { id: "4fUR9wznf2U&list", category: "عبد الرحمن السديس" },
    { id: "1dbl_rk9HoA&list", category: "عبد الرحمن السديس" },
    { id: "VvgT3Ut188s&list", category: "عبد الرحمن السديس" },
    { id: "Tjtm9FW451Q&list", category: "عبد الرحمن السديس" },
    { id: "Cr_I04nItSg&list", category: "عبد الرحمن السديس" },
    { id: "IjR7Ypwqas4&list", category: "عبد الرحمن السديس" },
    { id: "TguD9EnMAYo&list", category: "عبد الرحمن السديس" },
    { id: "OuAXW6QkKHo&list", category: "عبد الرحمن السديس" },
    { id: "xYt1cThL8u0&list", category: "عبد الرحمن السديس" },
    { id: "dR02zlXn1t4&list", category: "عبد الرحمن السديس" },
    { id: "Nsl-wLqeiNM&list", category: "عبد الرحمن السديس" },
    { id: "fLkKIwF37tI&list", category: "عبد الرحمن السديس" },
    { id: "cVXzRhPsESU&list", category: "عبد الرحمن السديس" },
    { id: "3SISVo7oGBk&list", category: "عبد الرحمن السديس" },
    { id: "87FxUj-R3CU&list", category: "عبد الرحمن السديس" },
    { id: "oQ4IRZ91b94&list", category: "عبد الرحمن السديس" },
    { id: "34yOSWWseu8&list", category: "عبد الرحمن السديس" },
    { id: "8M2TUCyzOLg&list", category: "عبد الرحمن السديس" },
    { id: "Hn4BEJj0o4E&list", category: "عبد الرحمن السديس" },
    { id: "MSudnGcxnZI&list", category: "عبد الرحمن السديس" },
    { id: "mrAulcGf5E8&list", category: "عبد الرحمن السديس" },
    { id: "2Uwaadnzz7A&list", category: "عبد الرحمن السديس" },
    { id: "Z1ylGLYhr-8&list", category: "عبد الرحمن السديس" },
    { id: "Qdw9cfdxL3o&list", category: "عبد الرحمن السديس" },
    { id: "Ky9mlWm2yJU&list", category: "عبد الرحمن السديس" },
    { id: "4HH-_NMFyRM&list", category: "عبد الرحمن السديس" },
    { id: "2QnXFBYeb0o&list", category: "عبد الرحمن السديس" },
    { id: "bSKH-8FUXI0&list", category: "عبد الرحمن السديس" },
    { id: "w8Qvf6JMfMU&list", category: "عبد الرحمن السديس" },
    { id: "ft-CZUr-iJs&list", category: "عبد الرحمن السديس" },
    { id: "sRjauJ20ud0&list", category: "عبد الرحمن السديس" },
    { id: "yuYBgfJiuMo&list", category: "عبد الرحمن السديس" },
    { id: "TyFpGQ0nxMs&list", category: "عبد الرحمن السديس" },
    { id: "ekHFVfLwr0o&list", category: "عبد الرحمن السديس" },
    { id: "LzaV9ewGD84&list", category: "عبد الرحمن السديس" },
    { id: "ZP2W-MNnMbA&list", category: "عبد الرحمن السديس" },
    { id: "hglic8cSEkc&list", category: "عبد الرحمن السديس" },
    { id: "MLTM7ICoeBg&list", category: "عبد الرحمن السديس" },
    { id: "aFSJuZkLldI&list", category: "عبد الرحمن السديس" },
    { id: "suC3OGWDwLU&list", category: "عبد الرحمن السديس" },
    { id: "J_vBI3AHC4U&list", category: "عبد الرحمن السديس" },
    { id: "YaPIB2YyfGk&list", category: "عبد الرحمن السديس" },
    { id: "ZP8wSc6IVx8&list", category: "عبد الرحمن السديس" },
    { id: "0rbn4ozPXjQ&list", category: "عبد الرحمن السديس" },
    { id: "9Ptx_up8rXI&list", category: "عبد الرحمن السديس" },
    { id: "ZGf2gXvp-fw&list", category: "عبد الرحمن السديس" },
    { id: "KcY72F3K84U&list", category: "عبد الرحمن السديس" },
    { id: "wfwkgy4AfHU&list", category: "عبد الرحمن السديس" },
    { id: "ZO63uytcfEk&list", category: "عبد الرحمن السديس" },
    { id: "OTHI4rXk--A&list", category: "عبد الرحمن السديس" },
    { id: "vVuvA8uBsCU&list", category: "عبد الرحمن السديس" },
    { id: "vsSbMtxnCyA&list", category: "عبد الرحمن السديس" },
    { id: "ttedpVGTGAg&list", category: "عبد الرحمن السديس" },
    { id: "hORnmh6Z6oo&list", category: "عبد الرحمن السديس" },
    { id: "HGHm8ZLjics&list", category: "عبد الرحمن السديس" },
    { id: "cZbgjMPr4ok&list", category: "عبد الرحمن السديس" },
    { id: "bIwUD7lmFFo&list", category: "عبد الرحمن السديس" },
    { id: "S5Gh2o_9xhY&list", category: "عبد الرحمن السديس" },
    { id: "DqPsskOV37I&list", category: "عبد الرحمن السديس" },
    { id: "b0ZMyn9GtSg&list", category: "عبد الرحمن السديس" },
    { id: "mxm4Xawqusw&list", category: "عبد الرحمن السديس" },
    { id: "UVvxS1Tpqro&list", category: "عبد الرحمن السديس" },
    { id: "mxJrELaiO0U&list", category: "عبد الرحمن السديس" },
    { id: "05PPo4ukIv0&list", category: "عبد الرحمن السديس" },
    { id: "mGXUp9__uR8&list", category: "عبد الرحمن السديس" },
    { id: "z0076pFkIqQ&list", category: "عبد الرحمن السديس" },
    { id: "MyQMpfOAdlc&list", category: "عبد الرحمن السديس" },
  ],
  "فارس عباد": [
    { id: "prsdvjdEbfY&list", category: "فارس عباد" },
    { id: "uIFHCmkG5FI&list", category: "فارس عباد" },
    { id: "uzRGX2Jog9Q&list", category: "فارس عباد" },
    { id: "3PWivhusjXI&list", category: "فارس عباد" },
    { id: "mIX9Qt6wCAY&list", category: "فارس عباد" },
    { id: "mh7ao-jsiyI&list", category: "فارس عباد" },
    { id: "czCOjooKZLE&list", category: "فارس عباد" },
    { id: "gQgeKt8igrM&list", category: "فارس عباد" },
    { id: "n9fsj8ap1S4&list", category: "فارس عباد" },
    { id: "EIe_IWx9YeI&list", category: "فارس عباد" },
    { id: "RE1DMkpYPMw&list", category: "فارس عباد" },
    { id: "y1Eq7lzeFSE&list", category: "فارس عباد" },
    { id: "HovQ37tqc58&list", category: "فارس عباد" },
    { id: "9O5g82EBkzE&list", category: "فارس عباد" },
    { id: "NZG1uHdgAyw&list", category: "فارس عباد" },
    { id: "iu23ojlh7cs&list", category: "فارس عباد" },
    { id: "tWl13gCWFuc&list", category: "فارس عباد" },
    { id: "SN0LI3xNM-A&list", category: "فارس عباد" },
    { id: "64-p8D9oqWA&list", category: "فارس عباد" },
    { id: "NS5y5u6zoQ0&list", category: "فارس عباد" },
    { id: "wqqfH0mzZqY&list", category: "فارس عباد" },
    { id: "zREa9MGC2lc&list", category: "فارس عباد" },
    { id: "0QvpJQPPC9w&list", category: "فارس عباد" },
    { id: "kuHyl6mMOqc&list", category: "فارس عباد" },
    { id: "2xgQFdWaNrQ&list", category: "فارس عباد" },
    { id: "UbVoU4lrPSE&list", category: "فارس عباد" },
    { id: "RnlP7BzUtaQ&list", category: "فارس عباد" },
    { id: "Bg7R0_Wlef0&list", category: "فارس عباد" },
    { id: "MMZiaaQUWzY&list", category: "فارس عباد" },
    { id: "dvy9_4lH0Ss&list", category: "فارس عباد" },
    { id: "TEetPBJhqhw&list", category: "فارس عباد" },
    { id: "qCz1lTpwYkc&list", category: "فارس عباد" },
    { id: "lBpAeII5nYg&list", category: "فارس عباد" },
    { id: "CGC-SWToYU4&list", category: "فارس عباد" },
    { id: "9XxItNmJGVc&list", category: "فارس عباد" },
    { id: "8l7i9t27OJ4&list", category: "فارس عباد" },
    { id: "BJiJpXSf1sE&list", category: "فارس عباد" },
    { id: "j5QV6q1ZBQI&list", category: "فارس عباد" },
    { id: "jIdJ4HnG8gs&list", category: "فارس عباد" },
    { id: "05KZm9RyXgU&list", category: "فارس عباد" },
    { id: "vNBbgs6_n7s&list", category: "فارس عباد" },
    { id: "EkP1iXGg6rs&list", category: "فارس عباد" },
    { id: "ALMc7GBpt5s&list", category: "فارس عباد" },
    { id: "KtaOmblfMBY&list", category: "فارس عباد" },
    { id: "rV9alocynpM&list", category: "فارس عباد" },
    { id: "YhI4C1y21Oc&list", category: "فارس عباد" },
    { id: "W4khOR-j6tI&list", category: "فارس عباد" },
    { id: "eYBQkM65fcg&list", category: "فارس عباد" },
    { id: "aLDFnyo5jNw&list", category: "فارس عباد" },
    { id: "uWa0rSbmJuA&list", category: "فارس عباد" },
    { id: "XHYw4Py3OeI&list", category: "فارس عباد" },
    { id: "6hSMCuKHhw0&list", category: "فارس عباد" },
    { id: "PSMYBgynFWI&list", category: "فارس عباد" },
    { id: "iggtWVS6Dxo&list", category: "فارس عباد" },
    { id: "QSf814On4_w&list", category: "فارس عباد" },
    { id: "7bCx5o6bUFE&list", category: "فارس عباد" },
    { id: "_lts9rao6Cs&list", category: "فارس عباد" },
    { id: "zOx59bKdM-c&list", category: "فارس عباد" },
    { id: "zMWdRz3ZZG4&list", category: "فارس عباد" },
    { id: "zihCyfPWMdU&list", category: "فارس عباد" },
    { id: "GEOdEBSLRF4&list", category: "فارس عباد" },
    { id: "rlHsWCWyGu0&list", category: "فارس عباد" },
    { id: "Y9jr-doDFHM&list", category: "فارس عباد" },
    { id: "GTWf_ViVDgI&list", category: "فارس عباد" },
    { id: "VunSD1N59Kw&list", category: "فارس عباد" },
    { id: "xavxnjHX08g&list", category: "فارس عباد" },
    { id: "ghnCuVnfwnU&list", category: "فارس عباد" },
    { id: "8b0rPR-Ml4I&list", category: "فارس عباد" },
    { id: "Ca9_VsjglZE&list", category: "فارس عباد" },
    { id: "3LbQSIWpSJs&list", category: "فارس عباد" },
    { id: "pdW_KgtiND4&list", category: "فارس عباد" },
    { id: "4_t7uW619HE&list", category: "فارس عباد" },
    { id: "UmKkUf_j5Gk&list", category: "فارس عباد" },
    { id: "3EZYJHt-v7E&list", category: "فارس عباد" },
    { id: "Pw5nkeDcaho&list", category: "فارس عباد" },
    { id: "gQ69UMAjZMg&list", category: "فارس عباد" },
    { id: "TMILvV3h4yk&list", category: "فارس عباد" },
    { id: "FKL5o5rzZLU&list", category: "فارس عباد" },
    { id: "rDoizjxoBc4&list", category: "فارس عباد" },
    { id: "APQghBjqFwg&list", category: "فارس عباد" },
    { id: "cVN5GMPpz8Y&list", category: "فارس عباد" },
    { id: "A9HZN7ukpOA&list", category: "فارس عباد" },
    { id: "K4zgI_vCvMk&list", category: "فارس عباد" },
    { id: "922E-H__9Ck&list", category: "فارس عباد" },
    { id: "ZDO5hL2eu6c&list", category: "فارس عباد" },
    { id: "4b7EoSi-m-s&list", category: "فارس عباد" },
    { id: "ldmsGuzl54U&list", category: "فارس عباد" },
    { id: "O2eSGAcjJdU&list", category: "فارس عباد" },
    { id: "ci09eftkQrw&list", category: "فارس عباد" },
    { id: "p_owgpn-mmA&list", category: "فارس عباد" },
    { id: "50U4tvIY3BE&list", category: "فارس عباد" },
    { id: "EG1WUi5rIk0&list", category: "فارس عباد" },
    { id: "7QDPOePjOKg&list", category: "فارس عباد" },
    { id: "h5mrHscrq-s&list", category: "فارس عباد" },
    { id: "rH0j3ePEauE&list", category: "فارس عباد" },
    { id: "vjC2i9Qnj2A&list", category: "فارس عباد" },
    { id: "u2gjHZvODcY&list", category: "فارس عباد" },
    { id: "UdYXI1Dy9lQ&list", category: "فارس عباد" },
    { id: "pEv1JyZLgoY&list", category: "فارس عباد" },
    { id: "l-3zOvWdpy0&list", category: "فارس عباد" },
    { id: "Ta-qL4LkYCk&list", category: "فارس عباد" },
    { id: "YhIRD3AaDlM&list", category: "فارس عباد" },
    { id: "lXKdBvfJOnY&list", category: "فارس عباد" },
    { id: "Vj0jhRBsmo8&list", category: "فارس عباد" },
    { id: "jas1Z2iyiLs&list", category: "فارس عباد" },
    { id: "F6M1ZfpHkjk&list", category: "فارس عباد" },
    { id: "rjOPB8VSj9M&list", category: "فارس عباد" },
    { id: "IJhOVyTQh9M&list", category: "فارس عباد" },
    { id: "vT5UoRlgDeI&list", category: "فارس عباد" },
    { id: "kATHGh_2R38&list", category: "فارس عباد" },
    { id: "a354__VIqpA&list", category: "فارس عباد" },
    { id: "5lyKx33Z3HI&list", category: "فارس عباد" },
    { id: "OAxL52zG8B4&list", category: "فارس عباد" },
    { id: "eWbdmpTokdo&list", category: "فارس عباد" },
  ],
  "هاني الرفاعي": [
{ id: "xIg-ggzHwa4&list", category: "هاني الرفاعي" },
{ id: "foC4qw24BTI&list", category: "هاني الرفاعي" },
{ id: "wp4_Keb8mhA&list", category: "هاني الرفاعي" },
{ id: "US5SB93qerg&list", category: "هاني الرفاعي" },
{ id: "MamHZ4af1wY&list", category: "هاني الرفاعي" },
{ id: "BrhUQwgZ4D0&list", category: "هاني الرفاعي" },
{ id: "6N9n8iRX9F4&list", category: "هاني الرفاعي" },
{ id: "tvff03IS_1k&list", category: "هاني الرفاعي" },
{ id: "fGiDNIJZ1b8&list", category: "هاني الرفاعي" },
{ id: "mV0Q3gkc9_8&list", category: "هاني الرفاعي" },
{ id: "cBuENtRow-M&list", category: "هاني الرفاعي" },
{ id: "m-gZR4IltN4&list", category: "هاني الرفاعي" },
{ id: "V-pH-ito9dU&list", category: "هاني الرفاعي" },
{ id: "5tOwxnYBgfY&list", category: "هاني الرفاعي" },
{ id: "s05l7tAg0ZE&list", category: "هاني الرفاعي" },
{ id: "z-iKqnnc0Io&list", category: "هاني الرفاعي" },
{ id: "_vHgO4516uE&list", category: "هاني الرفاعي" },
{ id: "x8hqNgp-0Vk&list", category: "هاني الرفاعي" },
{ id: "E4iLG_pYIrY&list", category: "هاني الرفاعي" },
{ id: "5GkThCygIyg&list", category: "هاني الرفاعي" },
{ id: "EBpUVt4phu8&list", category: "هاني الرفاعي" },
{ id: "uMx1jze0_Gw&list", category: "هاني الرفاعي" },
{ id: "DWOEuunJ8hk&list", category: "هاني الرفاعي" },
{ id: "Ii1Y0TfuRrE&list", category: "هاني الرفاعي" },
{ id: "0ves_OjjW0I&list", category: "هاني الرفاعي" },
{ id: "Xfh-SPPj-hM&list", category: "هاني الرفاعي" },
{ id: "A2ukmqc8ZVE&list", category: "هاني الرفاعي" },
{ id: "GI51ZqTCZ6I&list", category: "هاني الرفاعي" },
{ id: "oUVay3I8SsI&list", category: "هاني الرفاعي" },
{ id: "io6PoLkcylM&list", category: "هاني الرفاعي" },
{ id: "nSiiMIMq4yQ&list", category: "هاني الرفاعي" },
{ id: "osKaRa-Z7cA&list", category: "هاني الرفاعي" },
{ id: "8dtrwYaDPpw&list", category: "هاني الرفاعي" },
{ id: "Ekus964KO54&list", category: "هاني الرفاعي" },
{ id: "C9rEsRSILIM&list", category: "هاني الرفاعي" },
{ id: "fIoZCeD1t3I&list", category: "هاني الرفاعي" },
{ id: "E1bBkpgtlcM&list", category: "هاني الرفاعي" },
{ id: "ulN_aexJ1X4&list", category: "هاني الرفاعي" },
{ id: "xYwDek_wUts&list", category: "هاني الرفاعي" },
{ id: "003jtIfHMNo&list", category: "هاني الرفاعي" },
{ id: "snMrM32jSaI&list", category: "هاني الرفاعي" },
{ id: "58gngSmJecc&list", category: "هاني الرفاعي" },
{ id: "nNGPdyZ1Y84&list", category: "هاني الرفاعي" },
{ id: "FeM7-1URmoQ&list", category: "هاني الرفاعي" },
{ id: "48eJCxiD6c0&list", category: "هاني الرفاعي" },
{ id: "4vvWKSMjW6M&list", category: "هاني الرفاعي" },
{ id: "2Lh3-9aMZHY&list", category: "هاني الرفاعي" },
{ id: "6gGxTw3kHz4&list", category: "هاني الرفاعي" },
{ id: "zoixy_q9yRY&list", category: "هاني الرفاعي" },
{ id: "FLeOlPpcIj4&list", category: "هاني الرفاعي" },
{ id: "Nj-H5ZKGUyc&list", category: "هاني الرفاعي" },
{ id: "7INiNrnL1BY&list", category: "هاني الرفاعي" },
{ id: "gSdUAiA-5LA&list", category: "هاني الرفاعي" },
{ id: "ycfDDN1v5Po&list", category: "هاني الرفاعي" },
{ id: "iL-w8nNWOUM&list", category: "هاني الرفاعي" },
{ id: "9yN3I2-A5lc&list", category: "هاني الرفاعي" },
{ id: "CoPJKZwxbtI&list", category: "هاني الرفاعي" },
{ id: "kvqZuyQt5Wc&list", category: "هاني الرفاعي" },
{ id: "u7k_bEHdWm0&list", category: "هاني الرفاعي" },
{ id: "ntUf5VPGb_o&list", category: "هاني الرفاعي" },
{ id: "BNNVlGvEtPI&list", category: "هاني الرفاعي" },
{ id: "rUxx-rBBFcM&list", category: "هاني الرفاعي" },
{ id: "2TiU9FGVRsE&list", category: "هاني الرفاعي" },
{ id: "FE5MRGnmBDs&list", category: "هاني الرفاعي" },
{ id: "-FZpOJEps40&list", category: "هاني الرفاعي" },
{ id: "dUpKHz5S_Bg&list", category: "هاني الرفاعي" },
{ id: "b7v6qCtoWKA&list", category: "هاني الرفاعي" },
{ id: "4bZV1FFSZxo&list", category: "هاني الرفاعي" },
{ id: "P1yW4FbJZYA&list", category: "هاني الرفاعي" },
{ id: "cGSkdOvvxBk&list", category: "هاني الرفاعي" },
{ id: "8i_ARimlvvE&list", category: "هاني الرفاعي" },
{ id: "AhSUAojIcow&list", category: "هاني الرفاعي" },
{ id: "yzy5XQkDy7Y&list", category: "هاني الرفاعي" },
{ id: "uVWHy47Z3Aw&list", category: "هاني الرفاعي" },
{ id: "36GAX4ocQjY&list", category: "هاني الرفاعي" },
{ id: "nAwfBC3q95w&list", category: "هاني الرفاعي" },
{ id: "xp5WoMCqfUo&list", category: "هاني الرفاعي" },
{ id: "c7PTuh6A0bU&list", category: "هاني الرفاعي" },
{ id: "X5D50NhflvY&list", category: "هاني الرفاعي" },
{ id: "pYUwA6BpIlo&list", category: "هاني الرفاعي" },
{ id: "UpOEqXzp-2s&list", category: "هاني الرفاعي" },
{ id: "RXa-dMteCU0&list", category: "هاني الرفاعي" },
{ id: "2zdsLnX41Ig&list", category: "هاني الرفاعي" },
{ id: "XDBi7rjc6uQ&list", category: "هاني الرفاعي" },
{ id: "gjexU2025O8&list", category: "هاني الرفاعي" },
{ id: "nqVOjWo3yno&list", category: "هاني الرفاعي" },
{ id: "BoeQv7VeI6A&list", category: "هاني الرفاعي" },
{ id: "C5xb7n09eyU&list", category: "هاني الرفاعي" },
{ id: "9YECfESNTCg&list", category: "هاني الرفاعي" },
{ id: "3JYAdFFo3r0&list", category: "هاني الرفاعي" },
{ id: "B8O7LkOCip8&list", category: "هاني الرفاعي" },
{ id: "YEHUNLXwxcY&list", category: "هاني الرفاعي" },
{ id: "nQCacRAflPA&list", category: "هاني الرفاعي" },
{ id: "lAks6vtN8aQ&list", category: "هاني الرفاعي" },
{ id: "ZvSGJZ2NP5I&list", category: "هاني الرفاعي" },
{ id: "k5YedOcjxOM&list", category: "هاني الرفاعي" },
{ id: "d8k8lumm5D4&list", category: "هاني الرفاعي" },
{ id: "RDWWExNAWiA&list", category: "هاني الرفاعي" },
{ id: "JL5zJVT1sWo&list", category: "هاني الرفاعي" },
{ id: "ICXTzZBliQM&list", category: "هاني الرفاعي" },
{ id: "q3nFAPBK5-Y&list", category: "هاني الرفاعي" },
{ id: "51mIWcsR-ic&list", category: "هاني الرفاعي" },
{ id: "beDqs0bt_Ro&list", category: "هاني الرفاعي" },
{ id: "FSkeM9h5qNc&list", category: "هاني الرفاعي" },
{ id: "gLh02-2F-Vo&list", category: "هاني الرفاعي" },
{ id: "r4eQ_wi-RsQ&list", category: "هاني الرفاعي" },
{ id: "VESoDgV0eBQ&list", category: "هاني الرفاعي" },
{ id: "qb_otaNeOqs&list", category: "هاني الرفاعي" },
{ id: "HDWkeuoESfo&list", category: "هاني الرفاعي" },
{ id: "HWYYXUuOAnE&list", category: "هاني الرفاعي" },
{ id: "DWcte4IVSaM&list", category: "هاني الرفاعي" },
{ id: "tdMPX71IsLQ&list", category: "هاني الرفاعي" },
{ id: "REvmckxCof4&list", category: "هاني الرفاعي" },
{ id: "drMkDOo-Ifs&list", category: "هاني الرفاعي" },
{ id: "h9iWvw5oRKg&list", category: "هاني الرفاعي" },
  ],
};
 
// ===== قائمة الأقسام =====
const CATEGORIES = [
  "مشاري العفاسي",
  "عبد الباسط عبد الصمد",
  "محمد صديق المنشاوي",
  "ماهر المعيقلي",
  "سعد الغامدي",
  "أحمد العجمي",
  "عبد الرحمن السديس",
  "فارس عباد",
  "هاني الرفاعي",
];
 
// ===== CLEAN VIDEO ID =====
// يزيل أي بارامترات زائدة مثل &list=... أو ?si=... ويبقي الـ ID النظيف فقط
function cleanVideoId(id) {
  if (!id) return "";
  return id.split('&')[0].split('?')[0].trim();
}
 
// ===== TITLE CACHE =====
const TITLE_CACHE_KEY = "yt_title_cache_v1";
 
function getTitleCache() {
  try { return JSON.parse(localStorage.getItem(TITLE_CACHE_KEY) || "{}"); }
  catch { return {}; }
}
function saveTitleCache(cache) {
  try { localStorage.setItem(TITLE_CACHE_KEY, JSON.stringify(cache)); }
  catch {}
}
 
// ===== FETCH TITLE =====
async function fetchVideoTitle(id) {
  const cleanId = cleanVideoId(id);
 
  if (!cleanId) {
    console.warn("❌ ID فاضي تم تجاهله");
    return null;
  }
 
  const cache = getTitleCache();
  if (cache[cleanId]) return cache[cleanId];
 
  try {
    const res = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${cleanId}&format=json`
    );
 
    if (!res.ok) throw new Error();
 
    const d = await res.json();
    const title = d.title || cleanId;
 
    const c = getTitleCache();
    c[cleanId] = title;
    saveTitleCache(c);
 
    return title;
 
  } catch {
    return cleanId;
  }
}
 
// ===== ENRICH VIDEOS =====
async function enrichVideos(videos) {
  const cache = getTitleCache();
 
  const validVideos = videos.filter(v => {
    if (!cleanVideoId(v.id)) {
      console.warn("❌ فيديو بدون ID:", v);
      return false;
    }
    return true;
  });
 
  const missing = validVideos.filter(v => !cache[cleanVideoId(v.id)]);
 
  const BATCH = 6;
  for (let i = 0; i < missing.length; i += BATCH) {
    await Promise.all(
      missing.slice(i, i + BATCH).map(v => fetchVideoTitle(v.id))
    );
  }
 
  const updated = getTitleCache();
 
  return videos.map(v => ({
    ...v,
    id: cleanVideoId(v.id),
    title: updated[cleanVideoId(v.id)] || v.title || cleanVideoId(v.id)
  }));
}
 
// ===== DATA — Lazy Proxy =====
// لا يُبنى أي قسم إلا عند أول طلب له → لا تجميد عند تحميل الصفحة
const _dataCache = {};
 
function _buildCat(cat) {
  if (_dataCache[cat]) return _dataCache[cat];
  const raw = cat === 'الكل'
    ? CATEGORIES.flatMap(c => DATA_RAW[c] || [])
    : (DATA_RAW[cat] || []);
  const cache = getTitleCache();
  _dataCache[cat] = raw
    .filter(v => cleanVideoId(v.id) !== "")
    .map(v => ({
      ...v,
      id: cleanVideoId(v.id),
      title: cache[cleanVideoId(v.id)] || "جاري التحميل..."
    }));
  return _dataCache[cat];
}
 
const DATA = new Proxy({}, {
  get(_, prop) {
    // دعم القراءة العادية لمفاتيح مثل الكل أو أي قسم
    if (prop in _dataCache) return _dataCache[prop];
    if (prop === 'الكل' || CATEGORIES.includes(prop)) return _buildCat(prop);
    return undefined;
  },
  set(_, prop, value) {
    // السماح بالتعديل من الخارج (مثل تحديث العناوين في section.html)
    _dataCache[prop] = value;
    return true;
  },
  has(_, prop) {
    return prop === 'الكل' || CATEGORIES.includes(prop);
  }
});
 
// ===== WATCH HISTORY =====
function getWatchHistory() {
  try { return JSON.parse(localStorage.getItem("watchHistory") || "[]"); }
  catch { return []; }
}
 
function addToWatchHistory(video) {
  if (!video.id) return;
 
  let h = getWatchHistory();
  h = h.filter(v => v.id !== video.id);
  h.unshift({ ...video, watchedAt: Date.now() });
  h = h.slice(0, 5);
 
  localStorage.setItem("watchHistory", JSON.stringify(h));
}
 
function timeAgo(ts) {
  const s = Math.floor((Date.now() - ts) / 1000);
  const m = Math.floor(s / 60), hr = Math.floor(m / 60),
        d = Math.floor(hr / 24), w = Math.floor(d / 7), mo = Math.floor(d / 30);
 
  if (mo > 0) return `منذ ${mo} شهر`;
  if (w  > 0) return `منذ ${w} أسبوع`;
  if (d  > 0) return `منذ ${d} يوم`;
  if (hr > 0) return `منذ ${hr} ساعة`;
  if (m  > 0) return `منذ ${m} دقيقة`;
  return "منذ لحظات";
}
 
function getYoutubeThumbnail(id) {
  const cleanId = cleanVideoId(id);
  if (!cleanId) return "";
  return `https://img.youtube.com/vi/${cleanId}/mqdefault.jpg`;
}
